name: 'Docker Build and Push'
description: 'Builds a Docker image and pushes it to an authenticated registry. Assumes gcloud and docker are authenticated.'

inputs:
  registry:
    description: 'The full registry path (e.g., us-west1-docker.pkg.dev)'
    required: true
  project_id:
    description: 'GCP Project ID'
    required: true
  repository:
    description: 'The repository name in Artifact Registry'
    required: true
  image_name:
    description: 'The name of the Docker image'
    required: true
  image_sha:
    description: 'The full SHA to tag the image with'
    required: true
  git_ref:
    description: 'The git ref (branch or tag) to use for cache tagging'
    required: true
  tag_latest:
    description: 'Whether to also tag the image as latest'
    required: false
    default: 'false'

outputs:
  image_uri:
    description: "The full URI of the pushed image with SHA tag"
    value: ${{ steps.set-outputs.outputs.image_uri }}
  short_sha:
    description: "The short 7-character SHA"
    value: ${{ steps.set-outputs.outputs.short_sha }}
  full_sha:
    description: "The full SHA used for tagging"
    value: ${{ inputs.image_sha }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      shell: bash
      run: |
        IMAGE_URI="${{ inputs.registry }}/${{ inputs.project_id }}/${{ inputs.repository }}/${{ inputs.image_name }}"
        IMAGE_TAG_SHA="$IMAGE_URI:${{ inputs.image_sha }}"
        
        # Create a sanitized cache tag from the git ref
        # Replaces / with -
        CACHE_TAG_NAME=$(echo "${{ inputs.git_ref }}" | sed 's/[^a-zA-Z0-9]/-/g')
        CACHE_IMAGE_TAG="$IMAGE_URI:cache-$CACHE_TAG_NAME"

        # Pull the cache image if it exists
        docker pull $CACHE_IMAGE_TAG || true

        # Build the new image, using the cache
        docker build --cache-from $CACHE_IMAGE_TAG -t $IMAGE_TAG_SHA -t $CACHE_IMAGE_TAG .

        # Push the sha-tagged image and the cache image
        docker push $IMAGE_TAG_SHA
        docker push $CACHE_IMAGE_TAG
        
        # Optionally, tag and push "latest"
        if [ "${{ inputs.tag_latest }}" == "true" ]; then
          echo "Tagging and pushing latest tag..."
          IMAGE_TAG_LATEST="$IMAGE_URI:latest"
          docker tag $IMAGE_TAG_SHA $IMAGE_TAG_LATEST
          docker push $IMAGE_TAG_LATEST
        fi

    - name: Set outputs
      id: set-outputs
      shell: bash
      run: |
        echo "image_uri=${{ inputs.registry }}/${{ inputs.project_id }}/${{ inputs.repository }}/${{ inputs.image_name }}:${{ inputs.image_sha }}" >> $GITHUB_OUTPUT
        echo "short_sha=$(echo ${{ inputs.image_sha }} | cut -c1-7)" >> $GITHUB_OUTPUT 