name: 'Docker Build and Push'
description: 'Builds a Docker image and pushes it to an authenticated registry. Assumes gcloud and docker are authenticated.'

inputs:
  registry:
    description: 'The full registry path (e.g., us-west1-docker.pkg.dev)'
    required: true
  project_id:
    description: 'GCP Project ID'
    required: true
  repository:
    description: 'The repository name in Artifact Registry'
    required: true
  image_name:
    description: 'The name of the Docker image'
    required: true
  image_sha:
    description: 'The full SHA to tag the image with'
    required: true
  tag_latest:
    description: 'Whether to also tag the image as latest'
    required: false
    default: 'false'

outputs:
  image_uri:
    description: "The full URI of the pushed image with SHA tag"
    value: ${{ steps.set-outputs.outputs.image_uri }}
  short_sha:
    description: "The short 7-character SHA"
    value: ${{ steps.set-outputs.outputs.short_sha }}
  full_sha:
    description: "The full SHA used for tagging"
    value: ${{ inputs.image_sha }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      shell: bash
      run: |
        IMAGE_URI="${{ inputs.registry }}/${{ inputs.project_id }}/${{ inputs.repository }}/${{ inputs.image_name }}"
        IMAGE_TAG_SHA="$IMAGE_URI:${{ inputs.image_sha }}"
        IMAGE_TAG_LATEST="$IMAGE_URI:latest"

        # Pull the latest image to leverage caching
        docker pull $IMAGE_TAG_LATEST || true

        docker build --cache-from $IMAGE_TAG_LATEST -t $IMAGE_TAG_SHA -t $IMAGE_TAG_LATEST .
        docker push $IMAGE_TAG_SHA
        docker push $IMAGE_TAG_LATEST

    - name: Set outputs
      id: set-outputs
      shell: bash
      run: |
        echo "image_uri=${{ inputs.registry }}/${{ inputs.project_id }}/${{ inputs.repository }}/${{ inputs.image_name }}:${{ inputs.image_sha }}" >> $GITHUB_OUTPUT
        echo "short_sha=$(echo ${{ inputs.image_sha }} | cut -c1-7)" >> $GITHUB_OUTPUT 